"""SACZ atmospheric field and region catalog for ERA5 data."""

from riskclima_sacz.libs import models

feature_collection = [
    models.FeatureCollection(
        variable="w",
        nc_name="w",
        source="era5",
        level=500,
        out_name="omega",
        features=[
            models.Feature(area="AB1", shape="AB_OMEGA500_1"),
            models.Feature(area="AB2", shape="AB_OMEGA500_2"),
            models.Feature(area="C1", shape="C_OMEGA500_1"),
            models.Feature(area="C2", shape="C_OMEGA500_2"),
            models.Feature(area="C3", shape="C_OMEGA500_3"),
            models.Feature(area="DE1", shape="DE_OMEGA500_1"),
            models.Feature(area="DE2", shape="DE_OMEGA500_2"),
        ],
    ),
    models.FeatureCollection(
        variable="z",
        nc_name="z",
        source="era5",
        level=500,
        out_name="hgt",
        features=[
            models.Feature(area="AB1", shape="AB_HGT500_1"),
            models.Feature(area="AB2", shape="AB_HGT500_2"),
            models.Feature(area="C1", shape="C_HGT500_1"),
            models.Feature(area="C2", shape="C_HGT500_2"),
            models.Feature(area="DE2", shape="DE_HGT500_2"),
            models.Feature(area="DE3", shape="DE_HGT500_3"),
        ],
    ),
    models.FeatureCollection(
        variable="u",
        nc_name="u",
        source="era5",
        level=200,
        out_name="uwnd",
        features=[
            models.Feature(area="AB1", shape="AB_U200_1"),
            models.Feature(area="AB2", shape="AB_U200_2"),
            models.Feature(area="AB3", shape="AB_U200_3"),
            models.Feature(area="C1", shape="C_U200_1"),
            models.Feature(area="C2", shape="C_U200_2"),
            models.Feature(area="C3", shape="C_U200_3"),
            models.Feature(area="DE1", shape="DE_U200_1"),
            models.Feature(area="DE2", shape="DE_U200_2"),
            models.Feature(area="DE3", shape="DE_U200_3"),
            models.Feature(area="DE4", shape="DE_U200_4"),
            models.Feature(area="DE5", shape="DE_U200_5"),
        ],
    ),
    models.FeatureCollection(
        variable="v",
        nc_name="v",
        source="era5",
        level=200,
        out_name="vwnd",
        features=[
            models.Feature(area="AB1", shape="AB_V200_1"),
            models.Feature(area="AB2", shape="AB_V200_2"),
            models.Feature(area="AB3", shape="AB_V200_3"),
            models.Feature(area="C1", shape="C_V200_1"),
            models.Feature(area="C2", shape="C_V200_2"),
            models.Feature(area="C3", shape="C_V200_3"),
            models.Feature(area="DE1", shape="DE_V200_1"),
            models.Feature(area="DE2", shape="DE_V200_2"),
            models.Feature(area="DE3", shape="DE_V200_3"),
            models.Feature(area="DE4", shape="DE_V200_4"),
        ],
    ),
    models.FeatureCollection(
        variable="div",
        nc_name="div",
        source="era5",
        level=200,
        out_name="div",
        features=[
            models.Feature(area="AB1", shape="AB_DIV200_1"),
            models.Feature(area="AB2", shape="AB_DIV200_2"),
            models.Feature(area="C1", shape="C_DIV200_1"),
            models.Feature(area="C2", shape="C_DIV200_2"),
            models.Feature(area="DE1", shape="DE_DIV200_1"),
            models.Feature(area="DE2", shape="DE_DIV200_2"),
        ],
    ),
    models.FeatureCollection(
        variable="vort",
        nc_name="vort",
        source="era5",
        level=200,
        out_name="vort",
        features=[
            models.Feature(area="AB1", shape="AB_VORT200_1"),
            models.Feature(area="AB2", shape="AB_VORT200_2"),
            models.Feature(area="AB3", shape="AB_VORT200_3"),
            models.Feature(area="C1", shape="C_VORT200_1"),
            models.Feature(area="C2", shape="C_VORT200_2"),
            models.Feature(area="C3", shape="C_VORT200_3"),
            models.Feature(area="DE1", shape="DE_VORT200_1"),
            models.Feature(area="DE2", shape="DE_VORT200_2"),
            models.Feature(area="DE3", shape="DE_VORT200_3"),
        ],
    ),
    models.FeatureCollection(
        variable="u",
        nc_name="u",
        source="era5",
        level=850,
        out_name="uwnd",
        features=[
            models.Feature(area="AB1", shape="AB_U850_1"),
            models.Feature(area="AB2", shape="AB_U850_2"),
            models.Feature(area="C1", shape="C_U850_1"),
            models.Feature(area="C2", shape="C_U850_2"),
            models.Feature(area="DE1", shape="DE_U850_1"),
        ],
    ),
    models.FeatureCollection(
        variable="v",
        nc_name="v",
        source="era5",
        level=850,
        out_name="vwnd",
        features=[
            models.Feature(area="AB1", shape="AB_V850_1"),
            models.Feature(area="AB2", shape="AB_V850_2"),
            models.Feature(area="AB3", shape="AB_V850_3"),
            models.Feature(area="C1", shape="C_V850_1"),
            models.Feature(area="C2", shape="C_V850_2"),
            models.Feature(area="C3", shape="C_V850_3"),
            models.Feature(area="DE1", shape="DE_V850_1"),
            models.Feature(area="DE2", shape="DE_V850_2"),
            models.Feature(area="DE3", shape="DE_V850_3"),
        ],
    ),
    models.FeatureCollection(
        variable="div",
        nc_name="div",
        source="era5",
        level=850,
        out_name="div",
        features=[
            models.Feature(area="AB1", shape="AB_DIV850_1"),
            models.Feature(area="AB2", shape="AB_DIV850_2"),
            models.Feature(area="C1", shape="C_DIV850_1"),
            models.Feature(area="C2", shape="C_DIV850_2"),
            models.Feature(area="DE1", shape="DE_DIV850_1"),
            models.Feature(area="DE2", shape="DE_DIV850_2"),
        ],
    ),
]
